# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Window_1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(878, 518)
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(660, 210, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.pushButton_1 = PrimaryPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(320, 470, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = PrimaryPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 470, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.Image_label = QtWidgets.QLabel(Form)
        self.Image_label.setGeometry(QtCore.QRect(30, 40, 521, 391))
        self.Image_label.setText("")
        self.Image_label.setObjectName("Image_label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(580, 360, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(580, 400, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_1.setGeometry(QtCore.QRect(630, 390, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.pushButton_3 = PrimaryPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(630, 450, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(630, 350, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = PrimaryPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(720, 450, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_1.setText(_translate("Form", "录入程序"))
        self.pushButton_1.setText(_translate("Form", "拍照"))
        self.pushButton_2.setText(_translate("Form", "打开摄像头"))
        self.label_2.setText(_translate("Form", "姓名："))
        self.label_5.setText(_translate("Form", "学号："))
        self.pushButton_3.setText(_translate("Form", "确认"))
        self.pushButton_4.setText(_translate("Form", "取消"))
from qfluentwidgets import PrimaryPushButton
